name: Scraping diario EMMSA

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  scraping:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas selenium

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run scraper
        run: python scraper2.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ArchBIV/*.csv
          git commit -m "Update volumen EMMSA" || echo "No changes"
          git push
